"""PostgreSQL abstraction layer.

Every SQL-touching module talks to Postgres through this module so that all
dialect specifics (placeholder style, upsert syntax, identifier quoting,
introspection, type mapping, transaction handling) live in exactly one place.

Centralizes all PostgreSQL access so the rest of the codebase stays database-agnostic.
"""

import threading
from contextlib import contextmanager
from typing import Any, Iterable, Sequence

import psycopg
from psycopg import sql as pgsql
from psycopg.rows import dict_row, tuple_row

from hybriddb.config import paths

# Placeholder used by all hand-written parameterised SQL ("%s" for psycopg).
PLACEHOLDER = "%s"

# Schema type (from metadata) -> PostgreSQL column type.
PG_TYPE_MAP = {
    "int": "BIGINT",
    "float": "DOUBLE PRECISION",
    "string": "TEXT",
    "boolean": "BOOLEAN",
    "unknown": "TEXT",
}

# Identity column definition for surrogate primary keys. BY DEFAULT (not ALWAYS)
# so snapshot restore / migration can re-insert explicit surrogate key values.
IDENTITY_PK = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"


def pg_type(schema_type: str) -> str:
    """Map a metadata schema type to a PostgreSQL column type."""
    return PG_TYPE_MAP.get(schema_type, "TEXT")


# ---------------------------------------------------------------------------
# Connections (pooled)
# ---------------------------------------------------------------------------
#
# Opening a fresh PostgreSQL connection per operation is expensive (TCP + auth +
# server startup). A small process-wide pool reuses idle connections instead.
# This changes no behavior — a pooled connection runs the same SQL with the
# same transaction semantics; it is just reused rather than reconnected.
#
# Thread-safety: a connection is only ever handed to one thread at a time
# (checkout removes it from the pool, release returns it), which preserves
# psycopg's single-threaded-per-connection rule. Callers that still call
# conn.close() instead of release() are safe — the connection is simply dropped
# from the pool (less reuse, never incorrect).

_POOL_MAX = 8
_pool: list = []
_pool_lock = threading.Lock()


def conninfo() -> str:
    """Build a libpq connection string from the centralised config."""
    return (
        f"host={paths.PG_HOST} port={paths.PG_PORT} dbname={paths.PG_DB} "
        f"user={paths.PG_USER} password={paths.PG_PASSWORD}"
    )


def _checkout() -> psycopg.Connection:
    """Reuse an idle pooled connection, or open a new one if the pool is empty."""
    with _pool_lock:
        while _pool:
            conn = _pool.pop()
            if not conn.closed:
                return conn
    return psycopg.connect(conninfo())


def connect(*, autocommit: bool = False, row_factory=None) -> psycopg.Connection:
    """Borrow a connection from the pool (or open one), configured for this call.

    autocommit=True  -> read-only / health-probe / DDL paths.
    autocommit=False -> transactional write paths (default).
    row_factory=dict_row gives dict-like rows.

    Return the connection with release() when done (callers that call .close()
    instead are still safe — they just forgo reuse).
    """
    conn = _checkout()
    # Reconfigure per checkout so a reused connection matches this call exactly.
    conn.autocommit = autocommit
    conn.row_factory = row_factory or tuple_row
    return conn


def dict_connect(*, autocommit: bool = False) -> psycopg.Connection:
    """connect() with dict_row rows."""
    return connect(autocommit=autocommit, row_factory=dict_row)


def release(conn) -> None:
    """Return a connection to the pool for reuse (rolling back any open
    transaction first so the next user gets a clean connection). Closes it if
    the pool is full or the connection is broken. Use this instead of close()."""
    if conn is None:
        return
    try:
        if conn.closed:
            return
        conn.rollback()  # clear any open transaction; no-op if already idle
    except Exception:
        try:
            conn.close()
        except Exception:
            pass
        return
    with _pool_lock:
        if len(_pool) < _POOL_MAX:
            _pool.append(conn)
            return
    try:
        conn.close()
    except Exception:
        pass


@contextmanager
def transaction(*, row_factory=None):
    """Context-managed connection + single transaction.

        with transaction() as (conn, cur):
            cur.execute(...)

    Commits on clean exit, rolls back on exception, returns the connection to
    the pool either way.
    """
    conn = connect(row_factory=row_factory)
    try:
        with conn.cursor() as cur:
            yield conn, cur
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        release(conn)


# ---------------------------------------------------------------------------
# Write helpers (parameterised, identifier-safe)
# ---------------------------------------------------------------------------

def insert(cur, table: str, row: dict) -> None:
    """Plain parameterised INSERT with quoted identifiers."""
    if not row:
        return
    cols = list(row.keys())
    stmt = pgsql.SQL("INSERT INTO {tbl} ({cols}) VALUES ({vals})").format(
        tbl=pgsql.Identifier(table),
        cols=pgsql.SQL(", ").join(pgsql.Identifier(c) for c in cols),
        vals=pgsql.SQL(", ").join(pgsql.Placeholder() for _ in cols),
    )
    cur.execute(stmt, [row[c] for c in cols])


def upsert(cur, table: str, row: dict, conflict_cols: Sequence[str],
           update: bool = True) -> None:
    """INSERT ... ON CONFLICT (conflict_cols) DO UPDATE / DO NOTHING.

    update=True  replaces INSERT OR REPLACE.
    update=False replaces INSERT OR IGNORE.
    """
    if not row:
        return
    cols = list(row.keys())
    insert_part = pgsql.SQL("INSERT INTO {tbl} ({cols}) VALUES ({vals})").format(
        tbl=pgsql.Identifier(table),
        cols=pgsql.SQL(", ").join(pgsql.Identifier(c) for c in cols),
        vals=pgsql.SQL(", ").join(pgsql.Placeholder() for _ in cols),
    )
    conflict = pgsql.SQL(" ON CONFLICT ({keys}) ").format(
        keys=pgsql.SQL(", ").join(pgsql.Identifier(c) for c in conflict_cols),
    )
    set_cols = [c for c in cols if c not in conflict_cols]
    if update and set_cols:
        action = pgsql.SQL("DO UPDATE SET {assigns}").format(
            assigns=pgsql.SQL(", ").join(
                pgsql.SQL("{c} = EXCLUDED.{c}").format(c=pgsql.Identifier(c))
                for c in set_cols
            ),
        )
    else:
        action = pgsql.SQL("DO NOTHING")
    cur.execute(insert_part + conflict + action, [row[c] for c in cols])


def fix_identity_sequences(cur, table: str) -> None:
    """After bulk inserts with explicit identity values, advance each identity
    sequence past the max stored value so future auto-generated keys don't
    collide. Safe to call on tables without identity columns (no-op)."""
    with cur.connection.cursor(row_factory=tuple_row) as icur:
        icur.execute(
            """
            SELECT column_name
            FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = %s
              AND is_identity = 'YES'
            """,
            (table,),
        )
        identity_cols = [r[0] for r in icur.fetchall()]
    for col in identity_cols:
        seq = pgsql.SQL("pg_get_serial_sequence({t}, {c})").format(
            t=pgsql.Literal(table), c=pgsql.Literal(col),
        )
        setval = pgsql.SQL(
            "SELECT setval({seq}, COALESCE((SELECT MAX({col}) FROM {tbl}), 1))"
        ).format(seq=seq, col=pgsql.Identifier(col), tbl=pgsql.Identifier(table))
        try:
            cur.execute(setval)
        except Exception:
            pass


# ---------------------------------------------------------------------------
# Introspection
# ---------------------------------------------------------------------------

def table_columns(conn, table: str) -> list[dict]:
    """Return [{'name','type','notnull','pk'}] for a table.

    Returns column metadata (name, type, notnull, pk) for a table.
    """
    with conn.cursor(row_factory=tuple_row) as cur:
        cur.execute(
            """
            SELECT c.column_name,
                   c.data_type,
                   (c.is_nullable = 'NO') AS notnull,
                   COALESCE(pk.is_pk, FALSE) AS is_pk
            FROM information_schema.columns c
            LEFT JOIN (
                SELECT kcu.column_name, TRUE AS is_pk
                FROM information_schema.table_constraints tc
                JOIN information_schema.key_column_usage kcu
                  ON tc.constraint_name = kcu.constraint_name
                 AND tc.table_schema = kcu.table_schema
                WHERE tc.constraint_type = 'PRIMARY KEY'
                  AND tc.table_schema = 'public'
                  AND tc.table_name = %s
            ) pk ON pk.column_name = c.column_name
            WHERE c.table_schema = 'public' AND c.table_name = %s
            ORDER BY c.ordinal_position
            """,
            (table, table),
        )
        return [
            {"name": r[0], "type": r[1], "notnull": bool(r[2]), "pk": bool(r[3])}
            for r in cur.fetchall()
        ]


def column_names(conn, table: str) -> list[str]:
    """Just the column names, in ordinal order."""
    return [c["name"] for c in table_columns(conn, table)]


def table_exists(conn, table: str) -> bool:
    with conn.cursor() as cur:
        cur.execute(
            "SELECT 1 FROM information_schema.tables "
            "WHERE table_schema='public' AND table_name=%s",
            (table,),
        )
        return cur.fetchone() is not None


def list_tables(conn) -> list[str]:
    """All user tables in the public schema."""
    with conn.cursor(row_factory=tuple_row) as cur:
        cur.execute(
            "SELECT tablename FROM pg_catalog.pg_tables "
            "WHERE schemaname='public' ORDER BY tablename"
        )
        return [r[0] for r in cur.fetchall()]


def drop_all_tables() -> None:
    """Drop every table in the public schema (full reset). Used by db_init /
    the reset menu to fully reset the database."""
    with transaction() as (conn, cur):
        cur.execute("DROP SCHEMA public CASCADE")
        cur.execute("CREATE SCHEMA public")


# ---------------------------------------------------------------------------
# Health
# ---------------------------------------------------------------------------

def health_check() -> bool:
    """True if PostgreSQL is reachable (used by the coordinator's backend probe)."""
    try:
        conn = connect(autocommit=True)
        try:
            with conn.cursor() as cur:
                cur.execute("SELECT 1")
                cur.fetchone()
            return True
        finally:
            release(conn)
    except Exception:
        return False
